
    CREATE DATABASE DEVDOJO
    GO

    USE DEVDOJO
    GO

    -- FOREIGN KEY: Chave estrangeira
    -- FUNCIONARIO -> DEPARTAMENTO

    DROP TABLE IF EXISTS FUNCIONARIO
    GO

    DROP TABLE IF EXISTS DEPARTAMENTO
    GO

    CREATE TABLE DEPARTAMENTO (
        -- ID_DEPARTAMENTO INT PRIMARY KEY,
        COD_DEPARTAMENTO VARCHAR(10) PRIMARY KEY,
        DESC_DEPARTAMENTO VARCHAR(30) NOT NULL
    )
    GO

    -- SELECT * FROM DEPARTAMENTO

    CREATE TABLE FUNCIONARIO (
        MATRICULA INT NOT NULL IDENTITY(1000, 10),
        NOME VARCHAR(100) NOT NULL, -- CONSTRAINT
        SOBRENOME VARCHAR(100) NOT NULL,
        -- IDADE INT, -- CHECK (IDADE >= 18),
        DT_NASCIMENTO DATE NOT NULL, --NULL
        CPF VARCHAR(11) NOT NULL UNIQUE,
        TELEFONE VARCHAR(9) NOT NULL,
        EMAIL VARCHAR(100) NOT NULL,

        COD_DEPARTAMENTO VARCHAR(10),

        DATA_CRIACAO DATETIME DEFAULT GETDATE(),

        CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (MATRICULA), -- NÃO ACEITA NULL, NÃO ACEITA REGISTROS DUPLICADOS: VALORES ÚNICOS
        CONSTRAINT CH_CHECA_NASCIMENTO CHECK (DT_NASCIMENTO >= '1900-01-01'),

        CONSTRAINT FK_COD_DEPARTAMENTO FOREIGN KEY (COD_DEPARTAMENTO)
        REFERENCES DEPARTAMENTO (COD_DEPARTAMENTO)
    )
    GO

    SELECT * FROM INFORMATION_SCHEMA.TABLES

/*

    /*
        Se uma tabela tiver referência "FOREIGN KEY" de outra tabela, se usa o comando a baixo para eliminar a
        restrição (FOREIGN KEY) antes de apagar a tabela desejada
    */
    ALTER TABLE FUNCIONARIO
    DROP CONSTRAINT FK_COD_DEPARTAMENTO
    GO

    --==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--==--

    ALTER TABLE FUNCIONARIO
    ADD CONSTRAINT DefineData DEFAULT GETDATE() FOR DATA_CRIACAO
    GO

    ALTER TABLE FUNCIONARIO
    ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (MATRICULA)

*/

    INSERT INTO DEPARTAMENTO
    VALUES ('DBZ', 'Dragonball Z'),
           ('CDZ', 'Cavaleiros do Zodíaco'),
           ('YuYu', 'Yu-Yu Hakusho')
    GO

    INSERT INTO FUNCIONARIO (NOME, SOBRENOME, DT_NASCIMENTO, CPF, TELEFONE, EMAIL, COD_DEPARTAMENTO)
    VALUES ('William', 'Suane', '2015-01-01', '12345678911', '924242424', 'william.suane@will.com', 'CDZ'),
           ('Wildnei', 'Suane', '2010-01-01', '12345678912', '652192424', 'wildnei.suane@wilnei.com', 'DBZ'),
           ('Fabricio', 'Chousa', '1991-01-01', '12345678930', '924242356', 'fabricio.chousa@chousa.com', 'YuYu')
    GO

    -- SELECT GETDATE()
    SELECT * FROM FUNCIONARIO
    SELECT * FROM DEPARTAMENTO
    GO
