
    CREATE DATABASE DEVDOJO
    GO

    USE DEVDOJO
    GO

 -- FUNCIONARIO -> DEPARTAMENTO

    DROP TABLE IF EXISTS FUNCIONARIO
    GO

    CREATE TABLE FUNCIONARIO (
        MATRICULA INT PRIMARY KEY,
        NOME VARCHAR(100) NOT NULL, --CONSTRAINT
        DT_NASCIMENTO DATE --NULL
    )
    GO

    INSERT INTO FUNCIONARIO
    VALUES (null, 'William Suane', '2020-01-10')
    GO

    SELECT * FROM FUNCIONARIO
